### ISSUE TITLE
Fails to generate image

### ISSUE THREAD

**Issue by faisalhsn** [SimoneRiccardi/video-to-plymouth#1]
As the title suggests, vid to plymouth fails to generate image. First time I didnt see that as an issue a rebooted but theme bugs. like first few seconds plays and morbs to text based theme. It doesnt sound like a good description but I hope you understand. 

What I tried :
1. I tried to apply default themes that came with plymouth and they worked. And 
2. I also tried to other vids but your tool fails to generate image everytime.

Here is the output:

```
==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux -g /boot/initramfs-linux.img --microcode /boot/intel-ucode.img linux
==> Starting build: '6.4.12-arch1-1'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [plymouth]
  -> Running build hook: [autodetect]
  -> Running build hook: [keyboard]
==> WARNING: Possibly missing firmware for module: 'xhci_pci'
  -> Running build hook: [keymap]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux.img'
zstd: error 70 : Write error : cannot write block : No space left on device 
bsdtar: Write error
bsdtar: Write error
==> ERROR: Image generation FAILED: 'bsdtar (step 1) reported an error'

```

**Comment by faizalhosan** [comment]
The tool works just great. It was a human error. I realized my boot partition was small so I increased partition size. Great tool nonetheless man!

**Comment by faisalhsn** [comment]
The tool works just great. It was a human error. I realized my boot partition was small so I increased partition size. Great tool nonetheless man!
